### ISSUE TITLE
[Suggestion] Testing specific scenarios as GitHub issues

### ISSUE THREAD

**Issue by ChrisMissal** [ryndrb/dota2bot#37]
Are you able to make use of the the [good first issue label](https://github.com/ryndrb/dota2bot/labels/good%20first%20issue)? It may be helpful for any areas in the codebase that others could tinker and test things that you haven't gotten to, or that aren't as high priority for yourself.

As far as documentation or "getting started", here's a few things I would like to see (at least for myself):

- What code changes need to be made to force certain hero picks in an all pick mode?
  - I could make the changes to force a 5v5, commit to a local branch so I can come back to it later
- What is available to communicate with bots when a human player is in game? such as warding, etc
- Where in the codebase can I add chat statements for debugging or comedic purposes? :)
- Are there any parts where the game engine can be mocked and unit tested with [busted](https://github.com/lunarmodules/busted) or another framework? The optimist in me thinks this could help spot breaking changes on patch releases

Keep up the good work!

**Comment by ryndrb** [comment]
> Are you able to make use of the the [good first issue label](https://github.com/ryndrb/dota2bot/labels/good%20first%20issue)? It may be helpful for any areas in the codebase that others could tinker and test things that you haven't gotten to, or that aren't as high priority for yourself.

Yes. And I don't mind.

> What code changes need to be made to force certain hero picks in an all pick mode?

https://github.com/ryndrb/dota2bot/blob/1ac9ca7764b0ed15c44e73f677ba0cbfc3406e8c/hero_selection.lua#L910 
is what selects a hero. You can remove the loop there, if you want. It's fairly straightforward. Just keep the IDs in mind and the type of heroes since this script uses lobby slots to assign roles.

> What is available to communicate with bots when a human player is in game? such as warding, etc

If only using the [Dota Bot Scripting API](https://developer.valvesoftware.com/wiki/Dota_Bot_Scripting), I think it's mainly just ``GetMostRecentPing``. If also using the general [Dota Lua API](https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Scripting/API) for a vscript, there might be some other stuff there, but I haven't really tinkered with it much apart from when I made ``Buff``.

> Where in the codebase can I add chat statements for debugging or comedic purposes? :)

Most of the ``GetDesire`` functions inside ``mode_`` files are called every frame. You can call ``print`` or ``ActionImmediate_Chat`` in them.

> Are there any parts where the game engine can be mocked and unit tested with [busted](https://github.com/lunarmodules/busted) or another framework?

I'm not sure since I have not used any unit testing frameworks with this script.
